-- EMPLOYEE table foreign keys
ALTER TABLE EMPLOYEE
ADD CONSTRAINT fk_super_ssn
FOREIGN KEY (Super_ssn) REFERENCES EMPLOYEE(Ssn)
ON DELETE SET NULL
ON UPDATE CASCADE;

ALTER TABLE EMPLOYEE
ADD CONSTRAINT fk_dno
FOREIGN KEY (Dno) REFERENCES DEPARTMENT(Dnumber)
ON DELETE RESTRICT
ON UPDATE CASCADE;

-- DEPARTMENT table foreign keys
ALTER TABLE DEPARTMENT
ADD CONSTRAINT fk_mgr_ssn
FOREIGN KEY (Mgr_ssn) REFERENCES EMPLOYEE(Ssn)
ON DELETE SET DEFAULT
ON UPDATE CASCADE;

-- DEPT_LOCATIONS table foreign keys
ALTER TABLE DEPT_LOCATIONS
ADD CONSTRAINT fk_dept_locations_dnumber
FOREIGN KEY (Dnumber) REFERENCES DEPARTMENT(Dnumber);

-- PROJECT table foreign keys
ALTER TABLE PROJECT
ADD CONSTRAINT fk_project_dnum
FOREIGN KEY (Dnum) REFERENCES DEPARTMENT(Dnumber);

-- WORKS_ON table foreign keys
ALTER TABLE WORKS_ON
ADD CONSTRAINT fk_works_on_essn
FOREIGN KEY (Essn) REFERENCES EMPLOYEE(Ssn);

ALTER TABLE WORKS_ON
ADD CONSTRAINT fk_works_on_pno
FOREIGN KEY (Pno) REFERENCES PROJECT(Pnumber);

-- DEPENDENT table foreign keys
ALTER TABLE DEPENDENT
ADD CONSTRAINT fk_dependent_essn
FOREIGN KEY (Essn) REFERENCES EMPLOYEE(Ssn);