name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build JAR
        run: ./mvnw clean package -DskipTests

      - name: SCP to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOYMENT_HOST }}
          username: ${{ secrets.DEPLOYMENT_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: ${{ secrets.DEPLOYMENT_PORT }}
          source: ./SleepDiver
          target: /home/${{ secrets.DEPLOYMENT_USERNAME }}/

      - name: Run the application on EC2
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.DEPLOYMENT_HOST }}
          username: ${{ secrets.DEPLOYMENT_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: ${{ secrets.DEPLOYMENT_PORT }}
          script: |
            nohup java -jar /home/${{ secrets.EC2_USER }}/springboot-app.jar > output.log 2>&1 &